# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - AlexandraMartinezEx2

on:
  push:
    branches:
      - dev_branch
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://containerservices.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a43ebafebfe2443b9db37bff7c7951f7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_afc60115a4cf42c892332a9a55028ee4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: containerservices.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a43ebafebfe2443b9db37bff7c7951f7 }}/microserviciomusic_img:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'AlexandraMartinezEx2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2711a938c88247f692a453d9a2e06ade }}
        images: 'containerservices.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a43ebafebfe2443b9db37bff7c7951f7 }}/microserviciomusic_img:${{ github.sha }}'